### ISSUE TITLE
Debug code left in Mac::PropertyList::ReadBinary?

### ISSUE THREAD

**Issue by trwyant** [briandfoy/mac-propertylist#14]
Thank you very much for your continued maintenance of Mac::PropertyList.

It appears that the _read_object() method of Mac::PropertyList::ReadBinary contains some extraneous say() statements. Were these left over from debugging? I am willing to prepare a pull request conditionalizing them on lexical $Debug, which gets initialized as in Mac::PropertyList itself.

I searched for 'say' statements other places, and did not find any.

**Comment by briandfoy** [comment]
Yeah, these are left over from work I'm trying to do to support 128-bit ints. You can do the PR as you say with conditionals, or delete them. Or I'll get to it next week.

**Comment by briandfoy** [comment]
Fixed in #15
