### ISSUE TITLE
xcode changes the XML DTD header

### ISSUE THREAD

**Issue by castaway** [briandfoy/mac-propertylist#27]
I'm rewriting plists used by xcode to generate apps, when I open the changed plist in xcode (v15), it doesn't complain, but it does rewrite the header:

```
-<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

Any objection to making this one the output of write, so that I get less changes in my app repo?

**Comment by briandfoy** [comment]
Sounds like a good change to me. If you'd like to make a PR, just check that the tests pass because the tests are probably using the old header. If not, I'll take a stab at it myself.

**Comment by briandfoy** [comment]
Heck, I looked at it and just fixed it. Mac-PropertyList-1.601 is on its way to CPAN. Let me know if you have any problems.
